spring:
  datasource:
    url: jdbc:h2:mem:moneydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console.enabled: true
  security:
    user:
      name: dev
      password: dev
